web:
  build: web
  command: gunicorn jashley_me.wsgi:application -w 2 -b 127.0.0.1:8001
  working_dir: /app/user/
  environment:
    PORT: 8001
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    REDIS_URL: 'redis://herokuRedis:6379/'
    DEBUG: 'True'
    SECRET_KEY: 'f6zxmto54(%4b56xv&xrpwku_=52yus19rz1nrsfy_(3=q*sal'
    NEVERCACHE_KEY: 'f6zxmto54(%4b56xv&xrpwku_=52yus19rz1nrsfy_(3=q*sal'
  ports:
    - '8001:8001'
  links:
    - herokuPostgresql
    - herokuRedis
herokuPostgresql:
  image: postgres
herokuRedis:
  image: redis
