web:
  build: web
  command: gunicorn jashley_me.wsgi:application -w 2 -b :8001
  working_dir: /app/user/
  environment:
    PORT: 8001
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    REDIS_URL: 'redis://herokuRedis:6379/'
  ports:
    - '8001:8001'
  links:
    - herokuPostgresql
    - herokuRedis
herokuPostgresql:
  image: postgres
herokuRedis:
  image: redis
