# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_scorecard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='answered_text',
            field=models.CharField(max_length=255),
        ),
    ]
